---
title: "ExploratoryDAProject1"
author: "Zhenyu Yang"
date: "2016Äê4ÔÂ6ÈÕ"
output:
   html_document:
     keep_md: yes
---
##Background

Measurements of electric power consumption in one household with a one-minute sampling rate over a period of almost 4 years. Different electrical quantities and some sub-metering values are available.

##Loading the data

```{r loading the data}
##Get dataset
fulldata <- read.csv("household_power_consumption.txt", header = T, sep = ";", na.strings = "?", check.names = F, stringsAsFactors = F, comment.char = "", quote = '\"')
fulldata$Date <- as.Date(fulldata$Date, format = "%d/%m/%Y")

##Subset dataset
data <- subset(fulldata, Date >= "2007-02-01" & Date <= "2007-02-02")
```

##Making Plots

###Plot 1

```{r plot 1}
##Plot 1
hist(data$Global_active_power, col="red", xlab = "Global Active Power (Kilowatts)", main ="Global Active Power")

##Save to PNG
dev.copy(png, file = "plot1.png", height=480, width=480)
dev.off()
```

###Plot 2

```{r plot 2}
##Manipulate datetime
Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "English") #my computer is in Chinese, so change it to english

datetime <- paste(as.Date(data$Date), data$Time)
data$DateTime <- as.POSIXct(datetime)

##Plot 2

plot(data$Global_active_power~data$DateTime, type ="l",
     ylab="Global Active Power (kilowatts)", xlab="")

##Save to PNG
dev.copy(png, file = "plot2.png", height=480, width=480)
dev.off()
```

###Plot 3

```{r plot 3}
##Plot 3
plot(data$Sub_metering_1~data$DateTime, type="l", ylab="Energy sub metering")
lines(data$Sub_metering_2~data$DateTime, type="l", col="red")
lines(data$Sub_metering_3~data$DateTime, type="l", col="blue")

legend("topright", col=c("black","red","blue"),lty=1, lwd=2,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))

##Save to PNG
dev.copy(png, file = "plot3.png", height=480, width=480)
dev.off()
```

###Plot 4

```{r plot 4}
##plot 4
par(mfrow=c(2,2), mar=c(4,4,2,2), oma=c(0,0,0,0))
plot(data$Global_active_power~data$DateTime, type ="l",
     ylab="Global Active Power", xlab="")
plot(data$Voltage~data$DateTime, type ="l",
     ylab="Voltage", xlab="datetime")
plot(data$Sub_metering_1~data$DateTime, type="l", ylab="Energy sub metering")
lines(data$Sub_metering_2~data$DateTime, type="l", col="red")
lines(data$Sub_metering_3~data$DateTime, type="l", col="blue")

legend("topright", col=c("black","red","blue"),lty=1, lwd=2,bty="n",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))

plot(data$Global_reactive_power~data$DateTime, type ="l",
     ylab="Global_reactive_power", xlab="datetime")

##Save to PNG
dev.copy(png, file = "plot4.png", height=480, width=480)
dev.off()
```

